### ISSUE TITLE
Remove dependence on redux-first-router

### ISSUE THREAD

**Issue by davemcorwin** [faceyspacey/redux-first-router-link#26]
This is a great module on its own and there are definitely use cases to use alongside different redux routing solutions. There is currently a fairly light dependence on redux-first-router in the source code, here are my suggestions, I'm more than happy to help out with this:

- Remove [`redirect`](https://github.com/faceyspacey/redux-first-router-link/blob/master/src/handlePress.js#L41): I believe this is to support feature parity with React-Router by allowing a `redirect` prop on the `Link` component. This seems unnecessary since we are just passing actions as the `to` prop in `Link` already. If one is using RFR, they could just do:
```
import { redirect } from 'redux-first-router'
import { foobar } from 'my-routes'
...
<Link to={redirect(foobar())}>...</Link>
...
```

instead of

```
import { foobar } from 'my-routes'
...
<Link to={foobar()} redirect={true}>...</Link>
...
```

- Either move `pathToAction` and `actionToPath` to a shared module with RFR such as redux-first-router-utils or something AND/OR allow this to be configured. When using a separate routing core one has to basically reimplement this anyways (in my case I'm supporting query params) so it be nice to be able to configure this alongside or in the absence of RFR, or even use the functions without RFR. (more on this later)

- Allow `selectLocationState` to be configured. This currently ties RFRL to whatever reducer key RFR uses to store the route map, so when using with RFR, I MUST have my routes in `location.routesMap`

- Either move `RoutesMap` type to a shared module with RFR such as redux-first-router-utils or something OR just duplicate in RFRL.

- To address the configuration I suggest something along the lines of RFRL exposing an `init` function to provide configuration. RFR would do this for you when starting up, but when using RFRL alone, you would be on the hook for it:
```
import { init } from 'redux-first-router-link'

// maybe even!
import { pathToAction } from 'redux-first-router-utils'

init({
  locationStateSelector: state => state.myLocation.myAwesomeRouteMap,
  actionToPath: <some_function>,
  pathToAction,
})
```

I know there are a few more items referenced in the tests, but those can be addressed in many ways.

Thoughts?

Dave

**Comment by faceyspacey** [comment]
Hey Dave, I can sense your an enthusiastic individual as I am...Why not make those contributions you "rolled" to RFR, rather than we machinate its Link package to support a competitor lol. 

PS. There's nothing wrong with copying/pasting. Perhaps debunking the dont-repeat-yourself thing (DRY) of OOP is one of the great React revelations. For all the abstractions and complexity DRY brings to future understanding, just repeat yourself in less abstract code. If you really need this package, hey, it's open source, do whatever u want with it. Just copy paste it brotha. My instinct is all this refactoring into something more abstract will be worth less in terms of overall contribution to the world, *but absolutely definitely LESS in for RFR*. And right now, while this product is new and on the come-up, that's the focus. Your request makes little business-sense. And also it's not gonna be a thing where everyone needs to make their own router. That won't be the case, just as it wasn't the case with its predecessors, React Router + Redux Little Router (99.9999% of everyone use top routers). If people have the skills and interest to build their own, they can certainly handle a package as simple as a Link package, as I'm sure u can.

Come on brother, u know better. Why didnt u just attempt to build query support into RFR via a pull request? If you had started down that path, you would have seen there was a comment in the Issues about it existing in the @next branch, which would have saved you time.

Basically what you're asking--from my perspective--doesn't make much sense. I'm all for peeling off things into small packages that can be used in a wider context. I don't feel a Link package is that case. The other router that needs this won't be in a better position as a result. UR ROUTER would do better with its own link package (with as much code as u want lifted from this). WHY? Cuz its simpler. U wanna make the package more abstract. U wanna take an otherwise straightforward package and add one level of complexity. It's not worth it for ya brother. Just copy/paste the code.

OR BETTER, come join me. I got some really slick stuff in the works ur gonna miss out on if u go ur own route with a router that eventually becomes incompatible. Maybe ur a far better coder than me, but this package is months upon months of refinement. I mean it's literally 4-6 months work on just this package. No Joke. That may seem rediculous to you, but there's a lot of complexities to doing the various things it does truly right and lots of thinking that may never be encoded in code revolving around various hurdles and traps that were avoided. But for real tho--there's zero point. This shit does a lot of stuff my friend; rolling ur own won't be able to do all the stuff this does any time soon. It does a lot, and the thinking behind decisions made is more important than code. Another option: fork it, but then what's the point; contribute back to it instead, so you will receive all the amazing features coming its way.

**Comment by faceyspacey** [comment]
...by the way u probably saw this:

https://github.com/faceyspacey/rudy-match-path

in the NavLink module. That was lifted from React Router. It's prefixed "rudy" because RFR will soon be renamed "rudy" (I have been fortunate enough to procure the package on NPM).

See: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/matchPath.js

That's where it's lifted from. That's just how the game goes. It's what I would do if i were u and was hell bent on my own router.
