### ISSUE TITLE
NavLink's `activeClassName` does not like querystrings

### ISSUE THREAD

**Issue by gouegd** [faceyspacey/redux-first-router-link#38]
Hi !
I'm using `NavLink` and its `activeClassName` prop.
I'm on a page that contains a querystring (blabla.com/path?group=42), and when the NavLink has the same URL (pathname and query), it doesn't apply the activeClassName. That's because `matchPath` ignores the query on the current location.
See [where matchPath is used](https://github.com/faceyspacey/redux-first-router-link/blob/master/src/NavLink.js#L65).

I think `matchPath` should be fixed, unless this would break something else relying on this limitation ?
As a workaround, one can pass an `isActive` function to do the proper thing.

**Comment by faceyspacey** [comment]
match-path is borrowed from React Router, and both packages in general rely on `path-to-regexp`:

https://github.com/faceyspacey/rudy-match-path/blob/master/src/index.js#L2
https://github.com/faceyspacey/redux-first-router/blob/master/src/pure-utils/pathToAction.js#L2

`path-to-regexp` only deals with paths, not queries. At the end of the day, since what we are talking about is nav links, most of the time query params aren't used.

That said, this package didn't start out with a `NavLink` component. The original thinking was that it's so damn easy to create such things now that all state is in redux, it should be left to userland to handle it. I added it just cuz it was quick and figured people would appreciate it. But ultimately it's low priority since it takes away from the main philosophy which revolves around redux mastery being all that you need. 

So I'm gonna close this. The challenge is also that we're doing lots of path-to-action parsing and vice versa and to now have to do query parsing here is just an unnecessary hit on perf when it's used so rarely in nav links.

**Comment by gouegd** [comment]
I get your point. The funny thing is I'm migrating from RR4 where it was working fine - but this is probably because I passed an object with pathname and query separated, while with RFR, we either pass the action or the whole URL.
It could be as simple as ignoring anything after '?' in both URLs, but I don't mind using the isValid prop for now, and perhaps building my own NavLink later on.
Thanks for the reply !

**Comment by faceyspacey** [comment]
no problem. I added the idea of ignoring.
