### ISSUE TITLE
Link hrefs are not prefixed with `#` when using createHashHistory

### ISSUE THREAD

**Issue by jamiemill** [faceyspacey/redux-first-router-link#50]
I'm using hash history, and I notice that the NavLinks work when clicked, but the `href` attributes contain a path without the `#` prefix, which means middle-clicking or copy-pasting the links to a new tab doesn't work.

Does this library currently try to support hash history, or would you consider supporting it?

**Comment by faceyspacey** [comment]
It's unknown as to whether it supports hash history :)

It would be nice to support it but very low on the priority list.

That said if you create regular hash links outside of the library you can navigate up and down the page just like on any HTML page. It just won't dispatch actions.

**Comment by faceyspacey** [comment]
hashes now have full support in the upcoming Ruby release:

https://github.com/faceyspacey/redux-first-router/commit/c9f5e6d6a13ef1edde046d223417005a0bd72c03

**Comment by srinivasdamam** [comment]
@faceyspacey facing the same issue as mentioned, is this released?

**Comment by faceyspacey** [comment]
not yet, but very soon.

**Comment by Guria** [comment]
Any updates here? It is very crucial feature for us.

**Comment by JacobSoderblom** [comment]
Hi, first of all sorry for writing in a closed issue. 

Is this ready to use? Because I can't get it to work at all, I might do it in a wrong way. I'm using `rudy-history` to create a hash history, but the links in this package does not use the `#` prefix.

Using version  2.1.1 for `redux-first-router` and 2.0.1 for `redux-first-router-link`.

**Comment by ScriptedAlchemy** [comment]
Can you provide an example?
Hashes seemed to work for me, but I spend a lot of time on Rudy-Respond so I may confuse this with the other ( RFR2 is only the core of Rudy, which is 10x larger)

**Comment by JacobSoderblom** [comment]
Yea sure! Here is a simple application https://codesandbox.io/s/6l8xm254qk if you open the links in a new tab they go to `/about` instead of `/#/about` for example.

I found out that if I add the `#` to the url in `toUrl.js` and then remove it in `handlePress.js` before trying to create the action, it works good.

**Comment by JacobSoderblom** [comment]
I think this [PR](https://github.com/faceyspacey/redux-first-router-link/pull/98) will solve my problems

**Comment by ScriptedAlchemy** [comment]
Can anyone help me verify it works (the pr) 

It’s 5 months old and we did a major release. If it’ll still work with RFR2 I’ll merge it immediately. Just neeed help validating it a little bit
