### ISSUE TITLE
Make <Link /> pure

### ISSUE THREAD

**Issue by gurre** [faceyspacey/redux-first-router-link#83]
Since `Link` is connected it's not pure and should therefore not be used inside of components. It is desirable to make it stateless to the equivalent of an anchor-tag.

**Comment by gurre** [comment]
One suggestion is to deligate using a handler-function.

**Comment by faceyspacey** [comment]
It can't be. Check the rudy-next branch for even more things it needs to listen to from the store. 

It's a small component, you are welcome to rip the code and make your own if you have simpler needs.

**Comment by faceyspacey** [comment]
Also the link package is in fact in the main RFR repo. So that's where u should check the rudy-next branch if interested.

It now listens for basename changes, additional routes added as part of code splitting, and only does active styles related listening if u are using that feature. It also only does additional listening related to relative links only if u are passing props for that feature. It's automated as possible in only listening to additional stuff if in fact u are using that feature. But if u didn't need some of the features u could make a simpler component that doesn't connect at all and only dispatches actions by bragging the store from context. That was what we originally did for ultimate perf, until other needs became important.

**Comment by gurre** [comment]
Ok cool, I see you have a lot of things planned. The problem is arrises when following idiomatic redux. Presentational Components must be pure and since an anchor tag is used inside of them it makes no sense to connect all your components that uses anchors. Let this sink in on you. The solution could be trivial.

I'll guess I could find a workaround by passing in `<Link />` inside of a handler.

**Comment by faceyspacey** [comment]
that does give me an idea to have a LinkLite component for those who don't want features that require listening to the store. It would essentially be the very original component we had here long ago.

In your case for now, I'd rip Link packages code and do exactly what u want. It's a small package and doesn't do much.

**Comment by gurre** [comment]
Perhaps expose an enhancer?

```
import { Link, linkEnhancer } from 'redux-first-router-link'

const ConnectedLink = linkEnhancer(Link)
```

What I really liked about your project is that it's stripped down of all nonsense react-router is doing.
