### ISSUE TITLE
Link's `tagName` prop should accept a component prop

### ISSUE THREAD

**Issue by quicksnap** [faceyspacey/redux-first-router-link#88]
We use Glamorous for inline CSS, and it's very helpful to pass a glamerous `<A>` component instead of a normal element.

In the current code, I can pass a component:

```
<Link tagName={glamorous.A as any} ...>
```

and it works correctly, but we get a propTypes warning. If we adjust the proptypes and type signature it should work fine with any component.

I'd issue a PR but I use TypeScript and am not really familiar with Flow. It should be pretty straightforward. If you're busy, I can try and give a quick try!

**Comment by quicksnap** [comment]
Looking at it further, it seems that with custom components, the href field isn't properly set.

**Comment by quicksnap** [comment]
Due to this logic, which can be adjusted: https://github.com/faceyspacey/redux-first-router-link/blob/master/src/Link.js#L77-L79

**Comment by faceyspacey** [comment]
It's fixed in the upcoming rudy release:

https://github.com/faceyspacey/redux-first-router/blob/rudy-next/src/Link/index.js#L85

It's about 1-2 weeks off.

Also `tagName` will be renamed to `component`.

For now, I'd just fork the Link component, it's pretty basic.

**Comment by faceyspacey** [comment]
What were the propTypes warnings by the way?

**Comment by quicksnap** [comment]
Just standard react propTypes warning saying that `tagName` wasn't a string, since I was passing it a component.

I just asked this in the Gitter chat, but what's new in the "Rudy" release? a lot of breaking changes? We're _just_ now integrating in a new project and it's been going great so far.

**Comment by faceyspacey** [comment]
i responded on gitter a few minutes ago.

unfortunately there will be, but they are all easy to change and there will be a migration guide. it will be well worth it. I wouldn't fret it, and just take it as it comes like users who've been using it for longer. It's the same overall premise for how you structure your app. Probably the most tedious change is instead of `payload`, it's `params`, `query`, `hash`, `state`. No more sticking to the original concept of FSAs (flux standard actions), and now it's about really *owning* that routing is an imperative part of the stack, so now those action key/vals constitute *FSRAs* (flux standard routing actions). 

Most other changes will be one-time config, and optional features you can opt out of until you're ready.
